# Top-level Makefile — ATHAD (Atmosphere of the Earth in the Hadean Eon)
# Builds the atmosphere model, the Python interface and the CLI interface.
# Forked from ATOM_Precipitation @ 1e3f319; the hydrosphere half is not part of ATHAD.

# -MMD -MP emits a .d file per object listing the headers it includes, so editing a
# header rebuilds every .cpp that pulls it in. Without this the build silently keeps
# stale objects — and ATHAD's physics lives almost entirely in headers (ThermoAtm.h,
# MoistConvection.h, SaturationAdjustment.h, MultiLayerRadiation.h, TurbulenceAtm.h),
# so a header edit that does not recompile is the normal case, not the exception.
CFLAGS = -ggdb -Wall -ffast-math -march=native -fPIC -std=c++17 -Ilib -Iatmosphere -Itinyxml2 -fopenmp -MMD -MP

# Common files for the shared lib(libcond.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATM_OBJ = atmosphere/cAtmosphereModel.o atmosphere/PrintMsg_Atm.o \
atmosphere/FileIO_Atm.o atmosphere/RHS_Atm_Turb.o \
atmosphere/RungeKutta_Atm_Turb.o atmosphere/MinMax_Atm.o \
atmosphere/Paraview_Atm.o atmosphere/InitValues_Atm.o \
atmosphere/Results_Atm.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATM_CLI_OBJ = cli/cond.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = atmosphere/cAtmosphereDefaults.cpp.inc atmosphere/AtmosphereLoadConfig.cpp.inc \
atmosphere/AtmosphereParams.h.inc python/atmosphere_pxd.pxi python/pycond.pyx \
python/config_cond.xml cli/config_cond.xml

COPY_FILE = pycond.so
TARGET_DIR = python

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: cond python $(target)

libcond.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ)
	ar rcs libcond.a $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ)

cond: libcond.a $(ATM_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATM_CLI_OBJ) -L. -lcond $(cFLAGS) -o cli/cond

$(PARAM_OUTPUTS): param.py
	rm -f atmosphere/cAtmosphereModel.o
	python param.py

analyze:
	analyze-build make

# Self-tests. These build standalone against the headers — no model state, no config —
# so they are cheap to run and safe to run first.
.PHONY: test test-saturation test-cond-column
test: test-saturation test-cond-column

test-saturation:
	$(CXX) -std=c++17 -Iatmosphere -Ilib -o test/saturation_selftest test/saturation_selftest.cpp
	./test/saturation_selftest

# The ATHAD_COND regime itself: the saturated sea surface, the two mixtures the column
# runs between, and the reason the dry adiabat cannot be used here. The config's
# composition and r_air are derived from these numbers, so this test guards them.
test-cond-column:
	$(CXX) -std=c++17 -Iatmosphere -Ilib -o test/cond_column_selftest test/cond_column_selftest.cpp
	./test/cond_column_selftest

python: libcond.a python/pycond.so

python/pycond.so: python/pycond.pyx python/cond.pxd libcond.a
	cd python && python setup.py build_ext --inplace

atmosphere/%.o: atmosphere/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

# Header dependencies emitted by -MMD, one .d per object. The '-' suppresses the
# "no such file" noise on the first build, before any .d exists.
DEPS = $(LIB_OBJ:.o=.d) $(ATM_OBJ:.o=.d) $(XML_OBJ:.o=.d) $(ATM_CLI_OBJ:.o=.d)
-include $(DEPS)

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATM_OBJ) $(XML_OBJ) $(ATM_CLI_OBJ) $(DEPS) $(PARAM_OUTPUTS) cli/cond libcond.a
	\rm -vf python/*.so python/*.o python/pycond.cpp
	\rm -rf python/build/
