# pxi files
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME

import sys

from cond cimport cAtmosphereModel

from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector

class Model:
    """
    ATHAD Model Object
    """
    def __init__(self):
        self.atmosphere = Atmosphere()
        self.output_path = ""
        self.time_slice = 0
        self.config_xml = ""

    def run_atm(self, t_s, output_path, cfg_xml):
        self.time_slice = t_s
        self.output_path = output_path
        self.config_xml = cfg_xml
        print self.time_slice
        print self.output_path
        print self.config_xml
        self.atmosphere.load_config(self.config_xml)
        self.atmosphere.run_time_slice(self.time_slice)




cdef class Atmosphere:
    """
    Cython wrapper class for C++ class Atmosphere
    """
    cdef:
        cAtmosphereModel *_thisptr

    def __cinit__(Atmosphere self):
        # Initialize the "this pointer" to NULL so __dealloc__
        # knows if there is something to deallocate. Do not
        # call new cAtmosphereModel() here.
        self._thisptr = NULL

    def __init__(Atmosphere self):
        # Constructing the C++ object might raise std::bad_alloc
        # which is automatically converted to a Python MemoryError
        # by Cython. We therefore need to call "new cAtmosphereModel()" in
        # __init__ instead of __cinit__.
        self._thisptr = new cAtmosphereModel()

    def __dealloc__(Atmosphere self):
        # Only call del if the C++ object is alive,
        # or we will get a segfault.
        if self._thisptr != NULL:
            del self._thisptr

    cdef int _check_alive(Atmosphere self) except -1:
        # Because of the context manager protocol, the C++ object
        # might die before PyAtmosphere self is reclaimed.
        # We therefore need a small utility to check for the
        # availability of self._thisptr
        if self._thisptr == NULL:
            raise RuntimeError("Wrapped C++ object is deleted")
        else:
            return 0

    def load_config(Atmosphere self, str filename):
        self._check_alive()
        self._thisptr.LoadConfig(filename)
        return None

    def run(Atmosphere self):
        self._check_alive()
        self._thisptr.Run()
        return None

    def run_time_slice(Atmosphere self, int t):
        self._check_alive()
        self._thisptr.RunTimeSlice(t)
        return None

    def get_layer_heights(Atmosphere self):
        self._check_alive()
        return self._thisptr.get_layer_heights()

    # common section
    property output_path:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.output_path
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.output_path = <string> value
    
    property config_xml_path:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.config_xml_path
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.config_xml_path = <string> value
    
    property verbose:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.verbose
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.verbose = <bool> value
    
    property paraview_panorama_vts_flag:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.paraview_panorama_vts_flag
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.paraview_panorama_vts_flag = <bool> value
    
    property Coriolis:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.Coriolis
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.Coriolis = <double> value
    
    property centrifugal:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.centrifugal
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.centrifugal = <double> value
    
    property buoyancy:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.buoyancy
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.buoyancy = <double> value
    
    property r_Earth:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.r_Earth
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.r_Earth = <double> value
    
    property omega:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.omega
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.omega = <double> value
    
    property g:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.g
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.g = <double> value
    
    property time_start:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.time_start
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.time_start = <int> value
    
    property time_end:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.time_end
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.time_end = <int> value
    
    property time_step:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.time_step
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.time_step = <int> value
    
    property use_earthbyte_reconstruction:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.use_earthbyte_reconstruction
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.use_earthbyte_reconstruction = <bool> value
    
    property use_NASA_velocity:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.use_NASA_velocity
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.use_NASA_velocity = <bool> value
    
    property use_NASA_temperature:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.use_NASA_temperature
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.use_NASA_temperature = <bool> value
    
    property CategoryIceScheme:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.CategoryIceScheme
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.CategoryIceScheme = <int> value
    
    property p_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.p_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.p_0 = <double> value
    
    property t_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_0 = <double> value
    
    property t_surf_equator:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_surf_equator
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_surf_equator = <double> value
    
    property t_surf_pole:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_surf_pole
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_surf_pole = <double> value
    
    property cosmo_lapse_fraction:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cosmo_lapse_fraction
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cosmo_lapse_fraction = <double> value
    
    property t_skin:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_skin
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_skin = <double> value
    
    property t_skin_relax:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_skin_relax
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_skin_relax = <double> value
    
    property r_air:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.r_air
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.r_air = <double> value
    
    property r_0_water:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.r_0_water
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.r_0_water = <double> value
    
    property t_equat_modern:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_equat_modern
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_equat_modern = <double> value
    
    property rad_equator_short:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.rad_equator_short
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.rad_equator_short = <double> value
    
    property rad_pole_short:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.rad_pole_short
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.rad_pole_short = <double> value
    
    property rad_equator:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.rad_equator
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.rad_equator = <double> value
    
    property rad_pole:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.rad_pole
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.rad_pole = <double> value
    
    property sigma:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.sigma
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.sigma = <double> value
    
    property kappa_H2O:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.kappa_H2O
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.kappa_H2O = <double> value
    
    property kappa_CO2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.kappa_CO2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.kappa_CO2 = <double> value
    
    property kappa_bg:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.kappa_bg
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.kappa_bg = <double> value
    
    property geothermal_flux:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.geothermal_flux
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.geothermal_flux = <double> value
    
    property eps_residuum:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.eps_residuum
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.eps_residuum = <double> value
    
    property turb_model:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.turb_model
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.turb_model = <string> value
    
    property inviscid_spinup_iters:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.inviscid_spinup_iters
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.inviscid_spinup_iters = <int> value
    
    property inviscid_ramp_iters:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.inviscid_ramp_iters
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.inviscid_ramp_iters = <int> value
    
    property moist_phys_start_iter:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.moist_phys_start_iter
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.moist_phys_start_iter = <int> value
    
    property checkpoint_save_iter:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.checkpoint_save_iter
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.checkpoint_save_iter = <int> value
    
    property restart_from_iter:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.restart_from_iter
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.restart_from_iter = <int> value
    
    property restart_stride:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.restart_stride
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.restart_stride = <int> value
    
    property dt_visc:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.dt_visc
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.dt_visc = <double> value
    
    property dt_inviscid:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.dt_inviscid
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.dt_inviscid = <double> value
    
    # atmosphere section
    property nm:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.nm
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.nm = <int> value
    
    property checkpoint:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.checkpoint
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.checkpoint = <int> value
    
    property diagnostic_stride:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.diagnostic_stride
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.diagnostic_stride = <int> value
    
    property panorama_print:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.panorama_print
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.panorama_print = <int> value
    
    property coeff_Dalton:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.coeff_Dalton
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.coeff_Dalton = <double> value
    
    property convection_perturbation:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.convection_perturbation
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.convection_perturbation = <int> value
    
    property convection_mode:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.convection_mode
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.convection_mode = <int> value
    
    property iter_prec:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.iter_prec
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.iter_prec = <int> value
    
    property evap_model:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.evap_model
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.evap_model = <string> value
    
    property L_atm:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.L_atm
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.L_atm = <double> value
    
    property zeta:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.zeta
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.zeta = <double> value
    
    property tropopause_pole:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.tropopause_pole
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.tropopause_pole = <double> value
    
    property tropopause_equator:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.tropopause_equator
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.tropopause_equator = <double> value
    
    property cell_lat_scale:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cell_lat_scale
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cell_lat_scale = <double> value
    
    property cell_amp_mode:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cell_amp_mode
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cell_amp_mode = <int> value
    
    property n_cells_hemisphere:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.n_cells_hemisphere
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.n_cells_hemisphere = <int> value
    
    property albedo_surface:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.albedo_surface
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.albedo_surface = <double> value
    
    property albedo_cloud:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.albedo_cloud
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.albedo_cloud = <double> value
    
    property epsilon_equator:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.epsilon_equator
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.epsilon_equator = <double> value
    
    property epsilon_pole:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.epsilon_pole
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.epsilon_pole = <double> value
    
    property epsilon_tropopause:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.epsilon_tropopause
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.epsilon_tropopause = <double> value
    
    property re:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.re
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.re = <double> value
    
    property sc_WaterVapour:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.sc_WaterVapour
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.sc_WaterVapour = <double> value
    
    property sc_CO2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.sc_CO2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.sc_CO2 = <double> value
    
    property pr:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.pr
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.pr = <double> value
    
    property pr_turb:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.pr_turb
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.pr_turb = <double> value
    
    property abl_height:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.abl_height
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.abl_height = <double> value
    
    property x_H2O:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_H2O
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_H2O = <double> value
    
    property x_CO2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_CO2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_CO2 = <double> value
    
    property x_N2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_N2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_N2 = <double> value
    
    property x_CH4:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_CH4
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_CH4 = <double> value
    
    property x_NH3:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_NH3
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_NH3 = <double> value
    
    property x_H2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_H2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_H2 = <double> value
    
    property x_CO:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_CO
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_CO = <double> value
    
    property x_SO2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.x_SO2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.x_SO2 = <double> value
    
    property ep:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.ep
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.ep = <double> value
    
    property hp:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.hp
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.hp = <double> value
    
    property R_Air:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.R_Air
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.R_Air = <double> value
    
    property R_WaterVapour:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.R_WaterVapour
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.R_WaterVapour = <double> value
    
    property r_water_vapour:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.r_water_vapour
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.r_water_vapour = <double> value
    
    property R_co2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.R_co2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.R_co2 = <double> value
    
    property lv:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.lv
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.lv = <double> value
    
    property ls:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.ls
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.ls = <double> value
    
    property cp_l:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cp_l
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cp_l = <double> value
    
    property cv_l:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cv_l
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cv_l = <double> value
    
    property lamda:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.lamda
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.lamda = <double> value
    
    property r_co2:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.r_co2
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.r_co2 = <double> value
    
    property gam:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.gam
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.gam = <double> value
    
    property u_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.u_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.u_0 = <double> value
    
    property cloud_cap:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.cloud_cap
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.cloud_cap = <double> value
    
    property t_max_phys:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_max_phys
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_max_phys = <double> value
    
    property t_00:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_00
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_00 = <double> value
    
    property t_000:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.t_000
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.t_000 = <double> value
    
    property s_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.s_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.s_0 = <double> value
    
    property c_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.c_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.c_0 = <double> value
    
    property c_h2o_dry_top:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.c_h2o_dry_top
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.c_h2o_dry_top = <double> value
    
    property co2_0:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.co2_0
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.co2_0 = <double> value
    
    property co2_scale:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.co2_scale
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.co2_scale = <double> value
    
    property c_ocean:
        def __get__(Atmosphere self):
            self._check_alive()
            return self._thisptr.c_ocean
    
        def __set__(Atmosphere self, value):
            self._check_alive()
            self._thisptr.c_ocean = <double> value
    


    # The context manager protocol allows us to precisely
    # control the liftetime of the wrapped C++ object. del
    # is called deterministically and independently of
    # the Python garbage collection.

    def __enter__(Atmosphere self):
        self._check_alive()
        return self

    def __exit__(Atmosphere self, exc_tp, exc_val, exc_tb):
        if self._thisptr != NULL:
            del self._thisptr
            self._thisptr = NULL # inform __dealloc__
        return False # propagate exceptions




cdef public void PythonPrint(const char *s):
    print s,
    sys.stdout.flush()
